### ISSUE TITLE
Responsive Navbar

### ISSUE THREAD

**Issue by LoganxDev** [aztec-developers/azdev-static#4]
Navbar when shrinking as of right now has all of the links stacking, we should have it convert to a hamburger style menu.

![screen shot 2017-09-14 at 2 37 09 pm](https://user-images.githubusercontent.com/23465954/30456880-37ae90de-995a-11e7-9f08-714cc2f245d0.png)

Here's an example of shrunk down menu

**Comment by allidoisace** [comment]
Needs to look like this.

http://dribbble.s3.amazonaws.com/users/5973/screenshots/880056/lexicon-nuggets-2-ui-hamburger.png

**Comment by LoganxDev** [comment]
Not seeing anything here but I got the link in my email

**Comment by MichaelScript** [comment]
Closed as @LoganxDev and @myamout fixed this during todays meeting
